version: "3.9"

volumes:
  jenkins-data:
  jenkins-log:

networks:
  jenkins-net:

services:
  master:
    build: ./jenkins-master
    ports:
     - "50000:50000"
     - "8080:8080"
    volumes:
     - jenkins-log:/var/log/jenkins
     - jenkins-data:/var/jenkins_home
    networks:
     - jenkins-net

  nginx:
    build: ./jenkins-nginx
    ports:
     - "80:80"
    networks:
     - jenkins-net
